name: 'CI/CD'

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: docker build -t electrotech-front .
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: SSH into server
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
          SERVER_IP: ${{ secrets.DEPLOY_SERVER_ADDR }}
        run: |
          echo "$SSH_PASSWORD" > password
          chmod 600 password
          sshpass -f password ssh -o StrictHostKeyChecking=no root@${SERVER_IP} << 'EOF'
            cd /root/electrotech-front
            make restart
          EOF
